export const APPLOGOUT = 'APP/LOGOUT'

export const SHOWLOADER = 'APP/SHOWLOADER'
export const HIDELOADER = 'APP/HIDELOADER'
export const SHOWSNACKBAR = 'APP/SHOWSNACKBAR'
export const HIDESNACKBAR = 'APP/HIDESNACKBAR'
export const SHOWALERT = 'APP/SHOWALERT'
export const HIDEALERT = 'APP/HIDEALERT'
export const SHOWALERTDIALOG = 'APP/SHOWALERTDIALOG'
export const HIDEALERTDIALOG = 'APP/HIDEALERTDIALOG'

// sidebar
// export const ROOTMENUCHANGE = 'SIDEBAR/ROOTMENUCHANGE'
export const DRAWERTOOGLE = 'SIDEBAR/DRAWERTOOGLE'
export const FOLDERSTREE_TOGGLE = 'SIDEBAR/FOLDERSTREE_TOGGLE'
export const FOLDERSTREELOADSTART = 'SIDEBAR/FOLDERSTREELOADSTART'
export const FOLDERSTREELOADED = 'SIDEBAR/FOLDERSTREELOADED'
export const FOLDERSTREELOADFAIL = 'SIDEBAR/FOLDERSTREELOADFAIL'
export const FOLDERSTREESETINIT = 'SIDEBAR/FOLDERSTREESETINIT'
export const FOLDERS_TREE_CHANGE_PARENT_STARTED = 'SIDEBAR/FOLDERSTREECHANGEPARENTSTARTED'
export const FOLDERS_TREE_PARENT_CHANGED = 'SIDEBAR/FOLDERSTREEPARENTCHANGED'
export const FOLDERS_TREE_PARENT_CHANGED_FAIL = 'SIDEBAR/FOLDERSTREEPARENTCHANGEDFAIL'


/*
*****************************
    folderContent
*****************************
*/
export const FOLDER_CONTENT_LOADED = 'FOLDER_CONTENT/LOADED';
export const FOLDER_CONTENT_LOAD_FAILED = 'FOLDER_CONTENT/LOAD_FAILED';
export const FOLDER_CONTENT_ITEM_DELETED = 'FOLDER_CONTENT/ITEM_DELETED';
export const FOLDER_CONTENT_ITEM_DELETE_FAILED = 'FOLDER_CONTENT/ITEM_DELETE_FAILED';
export const FOLDER_CONTENT_ADD_FOLDER = 'FOLDER_CONTENT/ADD_FOLDER';
export const FOLDER_CONTENT_ADD_FOLDER_FAILED = 'FOLDER_CONTENT/ADD_FOLDER_FAILED';
export const FOLDER_CONTENT_FOLDER_ADDED = 'FOLDER_CONTENT/FOLDER_ADDED';
export const FOLDER_CONTENT_EDIT_FOLDER = 'FOLDER_CONTENT/EDIT_FOLDER';
export const FOLDER_CONTENT_FOLDER_EDITED = 'FOLDER_CONTENT/FOLDER_EDITED';
export const FOLDER_CONTENT_DELETE_FOLDER = 'FOLDER_CONTENT/DELETE_FOLDER';
export const FOLDER_CONTENT_FOLDER_DELETED = 'FOLDER_CONTENT/FOLDER_DELETED';
export const FOLDER_CONTENT_EDIT_FOLDER_FAILED = 'FOLDER_CONTENT/EDIT_FOLDER_FAILED';
export const FOLDER_CONTENT_DELETE_FOLDER_FAILED = 'FOLDER_CONTENT/DELETE_FOLDER_FAILED';
export const FOLDER_CONTENT_ITEM_ADDED = 'FOLDER_CONTENT/ITEM_ADDED';
export const FOLDER_CONTENT_ITEM_ADDED_FAILED = 'FOLDER_CONTENT/ITEM_ADDED_FAILED';
export const FOLDER_CONTENT_ITEM_EDITED = 'FOLDER_CONTENT/ITEM_EDITED';
export const FOLDER_CONTENT_ITEM_EDITED_FAILED = 'FOLDER_CONTENT/ITEM_EDITED_FAILED';
export const FOLDER_CONTENT_ITEM_DELETED_FAILED = 'FOLDER_CONTENT/ITEM_DELETED_FAILED';
export const FOLDER_CONTENT_SEARCH_CLICK = 'FOLDER_CONTENT/SEARCH_CLICK';
export const FOLDER_CONTENT_SORT_CLICK = 'FOLDER_CONTENT/SORT_CLICK';
export const FOLDER_CONTENT_SEARCH_LOADING = 'FOLDER_CONTENT/SEARCH_LOADING';
export const FOLDER_CONTENT_SEARCH_RESULTS_LOADED = 'FOLDER_CONTENT/SEARCH_LOADED';
export const FOLDER_CONTENT_SEARCH_RESULTS_FAILED = 'FOLDER_CONTENT/SEARCH_LOAD_FAILED';
export const FOLDER_CONTENT_CHANGE_PARENT_FOLDER = 'FOLDER_CONTENT/CHANGE_PARENT_FOLDER'
export const FOLDER_CONTENT_PARENT_FOLDER_CHANGED = 'FOLDER_CONTENT/PARENT_FOLDER_CHANGED'
export const FOLDER_CONTENT_PARENT_FOLDER_CHANGED_FAIL = 'FOLDER_CONTENT/PARENT_FOLDER_CHANGED_FAIL'
export const FOLDER_CONTENT_COPY_FOLDER = 'FOLDER_CONTENT/COPY_FOLDER';
export const FOLDER_CONTENT_FOLDER_COPIED = 'FOLDER_CONTENT/FOLDER_COPIED';
export const FOLDER_CONTENT_FOLDER_COPIED_FAILED = 'FOLDER_CONTENT/FOLDER_COPIED_FAILED';
export const FOLDER_CONTENT_MOVE_ITEM = 'FOLDER_CONTENT/MOVE_ITEM';
export const FOLDER_CONTENT_ITEM_MOVED = 'FOLDER_CONTENT/ITEM_MOVED';
export const FOLDER_CONTENT_ITEM_MOVED_FAILED = 'FOLDER_CONTENT/ITEM_MOVED_FAILED';
export const FOLDER_CONTENT_COPY_ITEM = 'FOLDER_CONTENT/COPY_ITEM';
export const FOLDER_CONTENT_ITEM_COPIED = 'FOLDER_CONTENT/ITEM_COPIED';
export const FOLDER_CONTENT_ITEM_COPIED_FAILED = 'FOLDER_CONTENT/ITEM_COPIED_FAILED';


export const USERS_LIST_LOADED = 'USERS/USERS_LOADED'
export const USERS_LIST_LOAD_FAILED = 'USERS/USERS_LOAD_FAILED'
export const USERS_LIST_ADD = 'USERS/USERS_ADD'
export const USERS_SELECTED = 'USERS/SELECTED'
export const USERS_LIST_ADDED = 'USERS/USERS_ADDED'
export const USERS_LIST_ADD_FAILED = 'USERS/USERS_ADD_FAILED'
export const USERS_LIST_DELETE = 'USERS/USERS_DELETE'
export const USERS_LIST_DELETED = 'USERS/USERS_DELETED'
export const USERS_LIST_DELETE_FAILED = 'USERS/USERS_DELETE_FAILED'
export const USERS_LIST_ROLE_DELETE = 'USERS/USERS_LIST_ROlE_DELETE'
export const USERS_LIST_ROLE_DELETED = 'USERS/USERS_LIST_ROLE_DELETED'
export const USERS_LIST_ROLE_DELETE_FAILED = 'USERS/USERS_ROLE_DELETE_FAILED'
export const USERS_LIST_CHECKED = 'USERS/USERS_LIST_CHECKED'
export const USERS_LIST_ALL_CHECKED = 'USERS/USERS_LIST_ALL_CHECKED'
export const USERS_LIST_MANAGE_STARTED = 'USERS/USERS_LIST_STARTED'
export const USERS_LIST_MANAGE = 'USERS/USERS_LIST_MANAGE'
export const USERS_LIST_MANAGE_FAILED = 'USERS/USERS_LIST_MANAGE_FAILED'

export const ROLE_LIST_LOADED = "ROLES/LOADED"
export const ROLE_LIST_LOAD_FAILED = "ROLES/LOAD_FAILED"
export const ROLE_CHANGE_WRITE_RIGHTS = "ROLES/WRITE_RIGHTS_CHANGE"
export const ROLE_ADD = "ROLES/ADD"
export const ROLE_DELETE = "ROLES/DELETE"
export const ROLE_FILTER = "ROLES/FILTER"
export const ROLE_SELECTED = "ROLES/SELECTED"
export const ROLE_SELECTED_FOLDER_TYPE = "ROLES/SELECTED_FOLDER_TYPE"

export const JOBS_FILTER = 'JOBS/FILTER'
export const USERS_JOBS_FILTER = 'USERS_JOBS/FILTER'
export const JOB_CANCEL = 'JOBS/CANCEL'
export const JOB_CANCELED = 'JOBS/CANCELED'
export const JOB_CANCEL_FAILED = 'JOBS/CANCEL_FAILED'
export const JOB_SQL_LOADED = 'JOBS/SQL_LOADED'
export const JOB_SQL_LOAD_FAILED = 'JOBS/SQL_LOAD_FAILED'
export const JOB_SQL_CLICK = 'JOBS/JOB_SQL_CLICK';
export const JOB_DIALOG_CLOSE = 'JOBS/JOB_DIALOG_CLOSE';
export const JOB_ADD_COMMENT = 'JOBS/ADD_COMMENT';
export const JOB_ADD_COMMENT_SUCCESS = 'JOBS/ADD_COMMENT_SUCCESS';
export const JOB_ADD_COMMENT_FAILED = 'JOBS/ADD_COMMENT_FAILED';
export const JOB_STATUS_HISTORY_LOADED = 'JOBS/STATUS_HISTORY_LOADED'
export const JOB_STATUS_HISTORY_LOAD_FAILED = 'JOBS/STATUS_HISTORY_LOAD_FAILED'
export const JOB_STATUS_HISTORY_CLICK = 'JOBS/STATUS_HISTORY_CLICK';
export const JOB_SHARE_LIST_CLICK = 'JOBS/SHARE_LIST_CLICK';

export const ASM_LIST_SHOW = "ASM/ASM_LIST_SHOW";
export const ASM_LIST_LOADED = "ASM/ASM_LIST_LOADED";
export const ASM_LIST_LOAD_FAILED = "ASM/ASM_LIST_LOAD_FAILED";
export const ASM_ADDED = "ASM/ASM_ADDED";
export const ASM_EDITED = "ASM/ASM_EDITED";
export const ASM_DELETED = "ASM/ASM_DELETED";
export const ASM_DATA_LOADED = "ASM/DESIGNER/DATA_LOADED";
export const ASM_DATA_LOAD_FAILED = "ASM/DESIGNER/DATA_LOAD_FAILED";
export const ASM_DESIGNER_CHANGE_ROOT_DATA = "ASM/DESIGNER/CHANGE_ROOT_DATA";
export const ASM_DESIGNER_CHANGE_SECURITY_SOURCE_DATA = "ASM/DESIGNER/CHANGE_SECURITY_SOURCE_DATA";
export const ASM_DESIGNER_SET_SECURITY_SOURCE_DATASET = "ASM/DESIGNER/SET_SECURITY_SOURCE_DATASET";
export const ASM_DESIGNER_ADD_SECURITY_SOURCE_FIELD = "ASM/DESIGNER/ADD_SECURITY_SOURCE_FIELD";
export const ASM_DESIGNER_SET_SECURITY_SOURCE_FIELD = "ASM/DESIGNER/SET_SECURITY_SOURCE_FIELD";
export const ASM_DESIGNER_DELETE_SECURITY_SOURCE_FIELD = "ASM/DESIGNER/DELETE_SECURITY_SOURCE_FIELD";
export const ASM_DESIGNER_ADD_SECURITY_SOURCE_SECURITY_FILTER = "ASM/DESIGNER/ADD_SECURITY_SOURCE_SECURITY_FILTER";
export const ASM_DESIGNER_DELETE_SECURITY_SOURCE_SECURITY_FILTER = "ASM/DESIGNER/DELETE_SECURITY_SOURCE_SECURITY_FILTER";
export const ASM_DESIGNER_ADD_SECURITY_FILTER_FIELD_MAPPING = "ASM/DESIGNER/ADD_SECURITY_FILTER_FIELD_MAPPING";
export const ASM_DESIGNER_UPDATE_SECURITY_FILTER_FIELD_MAPPING = "ASM/DESIGNER/UPDATE_SECURITY_FILTER_FIELD_MAPPING";
export const ASM_DESIGNER_DATA_TYPES_LOADED = "ASM/DESIGNER/DATA_TYPES_LOADED";
export const ASM_DESIGNER_DATA_TYPES_LOAD_FAILED = "ASM/DESIGNER/DATA_TYPES_LOAD_FAILED";
export const ASM_REFRESH_START = 'ASM/REFRESH_START';
export const ASM_REFRESH_FINISH = 'ASM/REFRESH_FINISH';

export const SF_ROLE_SETTINGS_LOADED = 'SF/LOADED'
export const SF_ROLE_SETTINGS_CHNAGED = 'SF/CHANGED'
export const SF_SET_LAST_FILTER_VALUE = 'SF/SET_LAST_FILTER_VALUE'
export const SF_ROLE_SETTINGS_COUNT_CHANGE = 'SF/COUNT_CHANGE'

export const FAVORITES_ADD_START = "FAVORITES/ADD_START"
export const FAVORITES_ADDED = "FAVORITES/ADDED"
export const FAVORITES_ADD_FAIL = "FAVORITES/ADD_FAIL"
export const FAVORITES_DELETE_START = "FAVORITES/DELETE_START"
export const FAVORITES_DELETED = "FAVORITES/DELETED"
export const FAVORITES_DELETE_FAIL = "FAVORITES/DELETE_FAIL"

export const SETTINGS_LOADED = "SEIINGS/LOADED"
export const SETTINGS_GET_JOURNAL_START = "SEIINGS/GET_JOURNAL_START"
export const SETTINGS_GET_JOURNAL_SUCCESS = "SEIINGS/GET_JOURNAL_SUCCESS"
export const SETTINGS_GET_JOURNAL_FAIL = "SEIINGS/GET_JOURNAL_FAIL"
export const SETTINGS_GET_FULL_JOURNAL_START = "SEIINGS/GET_FULL_JOURNAL_START"
export const SETTINGS_GET_FULL_JOURNAL_SUCCESS = "SEIINGS/GET_FULL_JOURNAL_SUCCESS"
export const SETTINGS_GET_FULL_JOURNAL_FAIL = "SEIINGS/GET_FULL_JOURNAL_FAIL"
export const SETTINGS_SET_START = "SEIINGS/SET_START"
export const SETTINGS_SET_SUCCESS = "SEIINGS/SET_SUCCESS"
export const SETTINGS_SET_FAIL = "SEIINGS/SET_FAIL"
export const SETTINGS_VALUE_CHANGED = "SEIINGS/VALUE_CHANGED"
export const SETTINGS_DISABLE_CHANGE = "SEIINGS/DISABLE_CHANGE"
export const SETTINGS_HISTORY_CLOSE = 'SETTINGS/HISTORY_CLOSE'

export const DARKTHEME ='DESIGN_SETTINGS/DARKTHEME'
export const LIGHTTHEME = 'DESIGN_SETTINGS/LIGHTTHEME'
export const DESIGN_SETTINGS_SET_VALUE = "DESIGN_SETTINGS/SET_VALUE"

// report filters and groupFilters
export const REPORT_FILTERS_LOADED = 'REPORT/FILTERS_LOADED'
export const REPORT_FILTER_CHANGED = 'REPORT/FILTER_CHANGED'
export const REPORT_FILTER_ADDED = 'REPORT/FILTER_ADDED'
export const REPORT_FILTER_DELETED = 'REPORT/FILTER_DELETED'
export const REPORT_FILTER_MOVED_BEFORE = 'REPORT/FILTER_MOVED_BEFORE'
export const REPORT_FILTER_MOVED_INTO = 'REPORT/FILTER_MOVED_INTO'
export const REPORT_GROUP_FILTER_CHANGED = 'REPORT/GROUP_FILTER_CHANGED'
export const REPORT_GROUP_FILTER_ADDED = 'REPORT/GROUP_FILTER_ADDED'
export const REPORT_GROUP_FILTER_DELETED = 'REPORT/GROUP_FILTER_DELETED'
export const REPORT_FILTERS_ORDINAL_CHANGED = 'REPORT/FILTERS_ORDINAL_CHANGED'

// report templates
export const REPORT_TEMPLATES_LOADED = 'REPORT/TEMPLATES_LOADED'
export const REPORT_TEMPLATES_LOAD_FAILED = 'REPORT/TEMPLATES_LOAD_FAILED'
export const REPORT_TEMPLATES_ADD_STARTED = 'REPORT/TEMPLATES_ADD_STARTED'
export const REPORT_TEMPLATES_ADDED = 'REPORT/TEMPLATES_ADDED'
export const REPORT_TEMPLATES_ADD_FAILED = 'REPORT/TEMPLATES_ADD_FAILED'
export const REPORT_TEMPLATES_DELETE_STARTED = 'REPORT/TEMPLATES_DELETE_STARTED'
export const REPORT_TEMPLATES_DELETED = 'REPORT/TEMPLATES_DELETED'
export const REPORT_TEMPLATES_DELETE_FAILED = 'REPORT/TEMPLATES_DELETE_FAILED'
export const REPORT_TEMPLATES_SET_DEFAULT_STARTED = 'REPORT/TEMPLATES_SET_DEFAULT_STARTED'
export const REPORT_TEMPLATES_SET_DEFAULT_SUCCESS = 'REPORT/TEMPLATES_SET_DEFAULT_SUCCESS'
export const REPORT_TEMPLATES_SET_DEFAULT_FAILED = 'REPORT/TEMPLATES_SET_DEFAULT_FAILED'

// schedule tasks
export const SCHEDULE_TASK_RUN_OK = "SCHEDULE_TASK/RUN_OK";
export const SCHEDULE_TASK_RUN_FAILED = "SCHEDULE_TASK/RUN_FAILED";
export const TASK_SWITCH = 'JOBS/TASK_SWITCH';
export const TASK_SWITCHED = 'JOBS/TASK_SWITCHED';
export const TASK_SWITCH_FAILED = 'JOBS/TASK_SWITCH_FAILED';

// OLAP
export const SET_AGG_MODAL_PARAMS = 'OLAP/SET_AGG_MODAL_PARAMS';

// NAVBAR
export const ADD_NAVBAR = 'NAVBAR/ADD_NAVBAR';
export const VIEW_ITEM_NAVBAR = 'NAVBAR/VIEW_ITEM_NAVBAR';
export const EDIT_ITEM_NAVBAR = 'NAVBAR/EDIT_ITEM_NAVBAR';
export const ADD_ITEM_NAVBAR = 'NAVBAR/ADD_ITEM_NAVBAR';
export const ADD_REPORT_NAVBAR = 'NAVBAR/ADD_REPORT_NAVBAR';
export const ADD_REPORT_STARTER_NAVBAR = 'NAVBAR/ADD_REPORT_STARTER_NAVBAR';