default:
  tags: 
    - heavy-runner
  image: dockerhub.repo.corp.tander.ru/maven:3.8.1-openjdk-16

variables:
  CI_DEBUG_TRACE: $TRACE
  MAGREPORT_HOME: "~/magreport2.1"
  REACT_APP_VERSION: 'cat version'
    
stages:
  - package

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "release-prod"
    - if: $CI_COMMIT_BRANCH == "main"


package:
  stage: package
  script:
    - mvn clean package $EXTRA_LOGGING
    - cat /root/.npm/_logs/*debug.log
  allow_failure: true
