default:
  tags: 
    - bi
  image: dockerhub.repo.corp.tander.ru/maven:3.8-openjdk-18

variables:
  CI: "false"
  MAGREPORT_HOME: "~/magreport2.1"
    
stages:
  - build

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "release-cloud"

build:
  stage: build
  variables:
    REACT_APP_VERSION: '1234'
  script:
    - TMP_REACT_APP_VERSION=`cat version`
    - if [ $CI_COMMIT_BRANCH == "release-prod" ]; then 
         REACT_APP_VERSION=$TMP_REACT_APP_VERSION.$CI_RUNNER_ID;
         ENVIRONMENT=prod;
      elif [ $CI_COMMIT_BRANCH == "release-test" ]; then
         REACT_APP_VERSION=$TMP_REACT_APP_VERSION.$CI_RUNNER_ID't';
         ENVIRONMENT=test;
      elif [ $CI_COMMIT_BRANCH == "release-cloud" ]; then
         REACT_APP_VERSION=$TMP_REACT_APP_VERSION.$CI_RUNNER_ID'c';
         ENVIRONMENT=cloud;
      else
         REACT_APP_VERSION=$TMP_REACT_APP_VERSION.$CI_RUNNER_ID'l';
         ENVIRONMENT=local;
      fi
    - echo "============================================================="
    - echo "Start building maven project"
    - echo "============================================================="
    - mvn clean package -Djavax.net.ssl.trustStore=$CI_PROJECT_DIR/cacerts
    - echo "============================================================="
    - echo "Start coping files"
    - echo "============================================================="
    - rm -rf $CI_PROJECT_DIR/package
    - mkdir -p $CI_PROJECT_DIR/package
    - mkdir -p $CI_PROJECT_DIR/package/etc/sysconfig
    - cp -f $CI_PROJECT_DIR/config/package/etc/sysconfig/magreport2 $CI_PROJECT_DIR/package/etc/sysconfig/magreport2
    - mkdir -p $CI_PROJECT_DIR/package/usr/lib/systemd/system
    - cp -f $CI_PROJECT_DIR/config/package/usr/lib/systemd/system/magreport2_"$ENVIRONMENT".service $CI_PROJECT_DIR/package/usr/lib/systemd/system/magreport2.service 
    - mkdir -p $CI_PROJECT_DIR/package/var/log/magreport2
    - touch $CI_PROJECT_DIR/package/var/log/magreport2/magreport2.log
    - mkdir -p $CI_PROJECT_DIR/package/var/magreport2/excel-templates
    - cp -rf  $CI_PROJECT_DIR/magreport-backend/src/main/resources/templates/* $CI_PROJECT_DIR/package/var/magreport2/excel-templates
    - mkdir -p $CI_PROJECT_DIR/package/var/magreport2
    - cp -rf $CI_PROJECT_DIR/config/package/var/magreport2/keystore $CI_PROJECT_DIR/package/var/magreport2
    - mkdir -p $CI_PROJECT_DIR/package/var/magreport2/jdbc
    - cp -rf $CI_PROJECT_DIR/magreport-backend/jdbc/* $CI_PROJECT_DIR/package/var/magreport2/jdbc
    - cp -f $CI_PROJECT_DIR/config/package/var/magreport2/application_"$ENVIRONMENT".properties $CI_PROJECT_DIR/package/var/magreport2/application.properties
    - cp -f $CI_PROJECT_DIR/config/package/var/magreport2/logback.xml $CI_PROJECT_DIR/package/var/magreport2/logback.xml
    - cp -f $CI_PROJECT_DIR/magreport-backend/target/magreport-backend-2.1.jar $CI_PROJECT_DIR/package/var/magreport2/magreport2.jar
    - echo "$REACT_APP_VERSION" > $CI_PROJECT_DIR/package/var/magreport2/version
    - cat $CI_PROJECT_DIR/package/var/magreport2/version
    - cp -f $CI_PROJECT_DIR/config/package/etc/sysconfig/magreport-admin $CI_PROJECT_DIR/package/etc/sysconfig/magreport-admin
    - cp -f $CI_PROJECT_DIR/config/package/usr/lib/systemd/system/magreport-admin.service $CI_PROJECT_DIR/package/usr/lib/systemd/system/magreport-admin.service
    - mkdir -p $CI_PROJECT_DIR/package/var/magreport2/magreport-admin
    - cp -f $CI_PROJECT_DIR/magreport-admin/target/magreport-admin-0.0.1-SNAPSHOT.jar $CI_PROJECT_DIR/package/var/magreport2/magreport-admin/magreport-admin.jar
    - cp -f $CI_PROJECT_DIR/config/package/var/magreport2/magreport-admin/application_"$ENVIRONMENT".properties $CI_PROJECT_DIR/package/var/magreport2/magreport-admin/application.properties
    - echo "============================================================="
    - echo "Preparing for SSH connect"
    - echo "============================================================="
    - mkdir -p /root/.ssh && touch /root/.ssh/known_hosts 
    - cp $CI_PROJECT_DIR/svc_magreport /root/.ssh/id_rsa_mg && chmod 600 /root/.ssh/id_rsa_mg
    - echo $SSH_FINGERPRINT >> /root/.ssh/known_hosts
    - echo "============================================================="
    - echo "Clean files"
    - echo "============================================================="
    - ssh -i /root/.ssh/id_rsa_mg $SSH_USER@$SSH_HOST cd /home/$SSH_USER
    - ssh -i /root/.ssh/id_rsa_mg $SSH_USER@$SSH_HOST rm -rf ./package
    - echo "============================================================="
    - echo "Start coping files to Test server"
    - echo "============================================================="
    - ssh -i /root/.ssh/id_rsa_mg $SSH_USER@$SSH_HOST mkdir /home/$SSH_USER/package
    - scp -i /root/.ssh/id_rsa_mg -r $CI_PROJECT_DIR/package/* $SSH_USER@$SSH_HOST:/home/$SSH_USER/package
    - echo "============================================================="
    - echo "Build rpm"
    - echo "============================================================="
    - ssh -i /root/.ssh/id_rsa_mg $SSH_USER@$SSH_HOST cd /home/"$SSH_USER"
    - ssh -i /root/.ssh/id_rsa_mg $SSH_USER@$SSH_HOST bash ./build-magreport2-rpm.sh
    - > 
      if [ $CI_COMMIT_BRANCH == "citest" ]; then 
        echo "============================================================="
        echo "Install rpm"
        echo "============================================================="
        ssh -i /root/.ssh/id_rsa_mg $SSH_USER@$SSH_HOST cd /home/$SSH_USER
        ssh -i /root/.ssh/id_rsa_mg $SSH_USER@$SSH_HOST sudo bash ./install-release.sh
      fi
