package ru.magnit.magreportbackend.dto.backup;

public enum BackupObjectTypeEnum {

    DATASOURCE,
    DATASOURCE_FOLDER,
    DATASET,
    DATASET_FOLDER,
    DATASET_FIELD,
    REPORT,
    REPORT_FOLDER,
    REPORT_FIELD,
    FILTER_REPORT_GROUP,
    FILTER_REPORT,
    FILTER_INSTANCE,
    FILTER_INSTANCE_FOLDER,
    FILTER_INSTANCE_FIELD,
    FILTER_REPORT_FIELD,
    SECURITY_FILTER,
    SECURITY_FILTER_FOLDER,
    SECURITY_FILTER_DATASET,
    SECURITY_FILTER_DATASET_FIELD,
    SCHEDULE,
    SCHEDULE_TASK,
    THEME,
    DESTINATION_USER,
    DESTINATION_EMAIL,
    DESTINATION_ROLE,
    SCHEDULE_SCHEDULE_TASK,
    ROLE
}
